accounts/urls.py
from django.urls import path 
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', views.indexView, name='home'),
    path('feed/', views.feedView, name='feed'),
    path('notifications/', views.notificationsView, name='notifications'),
    path('create_post/', PostCreate.as_view(), name='create_post_url'),
    path('recomend/', views.recomendView, name='recomend'),
    path('like/', views.like_post, name='like_url'),
    path('profile/<usname>', views.profileView, name='profile'),

    path('publication/<pub_id>', views.publicationView, name='publication'),
    path('publication_delete/<pub_id>', views.publicationDeleteView, name='pub_delete'),
    path('delete_ready/<pub_id>', views.publicationDeleteReadyView, name='delete_ready'),
    path('delete_cancel/<pub_id>', views.publicationDeleteCancelView, name='delete_cancel'),

    path('profile/profile_edit/', ProfileEdit.as_view(), name='profile_edit'),
    path('profile/<int:other_user>/subscribe', views.subscription_process, name='subscription'),
    path('login/', views.loginView, name='login_url'),
    path('register/', views.registerView, name='register_url'),
    path('logout/', LogoutView.as_view(next_page='/login'), name='logout'),
]

davadzhBlog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
    
] 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'accounts.views.handler404'
# handler500 = 'accounts.views.handler500'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Profile_info(models.Model):
    username = models.OneToOneField(User, default=1, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank='True')
    phone = models.CharField(max_length=50, null=True, blank='True')
    email = models.CharField(max_length=50, null=True, blank='True')
    profile_pic = models.ImageField(null=True, blank=True, default='default.png')
    subscribers = models.ManyToManyField(User, blank='True', related_name='subscribers')
    subscriptions = models.ManyToManyField(User, blank='True', related_name='subscriptions')

    def total_subs(self):
        return self.subscribers.count() 

    def total_subscr(self):
        return self.subscriptions.count() 
    
    def __str__(self):
        return self.username.username



class Notification(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    notification_from = models.CharField('Другой пользователь', max_length=300, blank=True)
    notification_text = models.CharField('Текст уведомления', max_length=300, blank=True)
    pub_id = models.IntegerField('Идентефикатор публикации', null=True, blank=True)
    not_date = models.DateTimeField('Дата уведомления', auto_now_add=True)

    def __str__(self):
        return self.notification_text



class Publication(models.Model):
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    pub_text = models.TextField('Введите текст публикации')
    pub_pic = models.ImageField('Загрузите фото', null=True)
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    pub_likes = models.ManyToManyField(User, blank='True', related_name='post_likes')

    def total_likes(self):
        return self.pub_likes.count() 

    #  auto_now_add=True

    def __str__(self):
        return self.pub_text


    
class Comment(models.Model):
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    pub = models.ForeignKey(Publication, on_delete=models.CASCADE)
    comment_text = models.TextField('Введите текст ...')
    comment_date = models.DateTimeField('Дата комментария', auto_now_add=True)

    def __str__(self):
        return self.comment_text

accounts/forms.py
from django import forms
from .models import Publication, Profile_info, Comment
from django.core.exceptions import ValidationError


class LikeForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['author']


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['author', 'pub_text', 'pub_pic']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'pub', 'comment_text']

    
class Profile_InfoForm(forms.ModelForm):
    class Meta:
        model = Profile_info
        fields = ['username', 'name', 'phone', 'email', 'profile_pic', 'subscribers', 'subscriptions']

    # def save(self):
    #     new_publication = Publication.objects.create(
    #         pub_text=self.cleaned_data['pub_text']
    #     )
    #     return new_publication

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.generic import View, RedirectView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from .models import Publication, Profile_info, Notification, Comment
from django.contrib.auth.models import User
from .forms import PublicationForm, Profile_InfoForm, CommentForm

from django.template.loader import render_to_string
from django.http import JsonResponse
import json

from datetime import datetime

# Create your views here.


# def handler404(request, exception, template_name="404.html"):
#     response = render_to_response("404.html")
#     response.status_code = 404
#     return response

# def handler500(request, exception, template_name="500.html"):
#     response = render_to_response("500.html")
#     response.status_code = 500
#     return response

    
def indexView(request):
    if request.user.is_authenticated:
        return redirect('profile/' + request.user.username)
    return redirect('login_url')


@login_required
def feedView(request):
    user_info = get_object_or_404(Profile_info, username=request.user.id)
    feed_pubs = Publication.objects.order_by('-pub_date')[:100]
    return render(request, 'feed.html', context={'feed_pubs': feed_pubs, 'user_info': user_info})


class PostCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = PublicationForm
        return render(request, 'create_post.html', context={'form': form})

    def post(self, request):
        # Заменяем в словаре значение id автора с дефолтного на юзер id
        a_id = str(request.user.id)
        request.POST = request.POST.copy()
        request.POST.update({'author': a_id})
        bound_form = PublicationForm(request.POST, request.FILES)
        if bound_form.is_valid():
            new_post = bound_form.save()
            return redirect('/profile/' + request.user.username)
        return render(request, 'create_post.html', context={'form': bound_form})


class ProfileEdit(LoginRequiredMixin, UpdateView):
    def get(self, request):
        form = Profile_InfoForm
        return render(request, 'profile_edit.html', context={'form': form})

    def post(self, request):
        # Заменяем в словаре значение id автора с дефолтного на юзер id
        a_id = str(request.user.id)
        user = get_object_or_404(Profile_info, username = request.user.id)
        print()
        print()
        print()
        print(request.POST)
        print()
        print()
        print()
        request.POST = request.POST.copy()
        request.POST.update({'username': a_id})

        for i in user.subscriptions.all():
            request.POST.update({'subscriptions': i.id})

        for i in user.subscribers.all():
            request.POST.update({'subscribers': i.id})

        bound_form = Profile_InfoForm(request.POST, request.FILES)
        current_data = Profile_info.objects.filter(username = a_id)
        current_data.delete()
        if bound_form.is_valid():
            profile_edited = bound_form.save()
            return redirect('/profile/' + request.user.username)
        return render(request, 'profile_edit.html', context={'form': bound_form})


@login_required
def recomendView(request):
    all_pubs = Publication.objects.order_by('-pub_date')[:100]
    return render(request, 'recomend.html', context={'all_pubs': all_pubs})


@login_required
def subscription_process(request, other_user):

    other_user_ = get_object_or_404(User, id = int(other_user))

    other_user = get_object_or_404(Profile_info, username = other_user_)
    this_user = get_object_or_404(Profile_info, username = request.user.id)
    this_user_ = request.user

    is_sub = False

    if other_user_ in this_user.subscriptions.all():
        print('Отписался')
        this_user.subscriptions.remove(other_user_)
        other_user.subscribers.remove(this_user_)
        is_sub = False
        notification_unsub = Notification.objects.filter(notification_from=this_user_.username, notification_text=' подписался(-ась) на вас.')
        if notification_unsub:
            for nt in notification_unsub:
                nt.delete()
    else:
        print('Подписался')
        this_user.subscriptions.add(other_user_)
        other_user.subscribers.add(this_user_)
        is_sub = True
        notification_sub = Notification.objects.create(username=other_user_,
                                                        notification_from=this_user_.username,
                                                        notification_text=' подписался(-ась) на вас.')        
            
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

@login_required
def like_post(request):
    print(request.POST)
    all_pubs = Publication.objects.order_by('-pub_date')[:100]
    user = request.user
    # obj = Publication.objects.get(id=request.POST.get('post_id'))
    obj = get_object_or_404(Publication, id=request.POST.get('post_id'))

    is_liked = False
    if user.is_authenticated:
        if user in obj.pub_likes.all():
            obj.pub_likes.remove(user)
            is_liked = False
            if user.username != obj.author.username:
                notification_unlike = Notification.objects.get(notification_from=user.username, 
                                                                notification_text=' нравится ваше фото.', 
                                                                pub_id=obj.id)
                if notification_unlike:
                    notification_unlike.delete()
        else:
            print(user.username)
            print(obj.author.username)
            obj.pub_likes.add(user)
            is_liked = True
            if user.username != obj.author.username:
                notification_like = Notification.objects.create(username=obj.author,
                                                            notification_from=user.username,
                                                            notification_text=' нравится ваше фото.',
                                                            pub_id=obj.id)

    context = {
        'pub': obj,
        'is_liked': is_liked,
        'total_likes': obj.total_likes()
    }
    if request.is_ajax():
        html = render_to_string('like_button.html', context, request=request)
        return JsonResponse({'cont': html})
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # return render(request, 'recomend.html', {'all_pubs': all_pubs, 'is_liked': is_liked, 'current_p_id': request.POST.get('post_id')})


@login_required
def notificationsView(request):
    nots = Notification.objects.filter(username=request.user).order_by('-not_date')[:30]
    return render(request, 'notifications.html', context={'nots': nots})


@login_required
def profileView(request, usname):
    current_user_User = get_object_or_404(User, username=usname)
    current_user = get_object_or_404(Profile_info, username=current_user_User.id)
    all_pubs = Publication.objects.filter(author = current_user_User.id).order_by('-pub_date')[:100]
    return render(request, 'profile.html', context={'all_pubs': all_pubs, 'current_user': current_user})


@login_required
def publicationView(request, pub_id):
    comments_of_pub = Comment.objects.filter(pub=pub_id).order_by('-comment_date')
    publication = get_object_or_404(Publication, id=pub_id)
    current_user = get_object_or_404(User, username=publication.author.username)
    comment_form = CommentForm
    context = { 
        'pub': publication,
        'current_user': current_user,
        'comment_form': comment_form,
        'comments_of_pub': comments_of_pub
    }
    if request.POST:
        a_id = str(request.user.id)
        p_id = str(pub_id)
        request.POST = request.POST.copy()
        request.POST.update({'author': a_id, 'pub': pub_id})
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return render(request, 'publication.html', context=context)


@login_required
def publicationDeleteView(request, pub_id):
    context = {'pub_id': pub_id}
    return render(request, 'publication_delete.html', context=context)


@login_required
def publicationDeleteReadyView(request, pub_id):
    need_to_delete = Publication.objects.get(id=pub_id)
    need_to_delete.delete()
    return redirect('/profile/' + request.user.username)


@login_required
def publicationDeleteCancelView(request, pub_id):
    return redirect('/publication/' + pub_id)


def loginView(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('recomend')
        else:
            is_failed = True
            user = AuthenticationForm()
            return render(request, 'registration/login.html', {'form': user, 'is_failed': is_failed})
    else:
        is_failed = False
        user = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': user, 'is_failed': is_failed})


def registerView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save() 
            reg_user = get_object_or_404(User, username = request.POST.get('username'))
            # reg_user = User.objects.filter(username = request.POST.get('username'))
            # Создание поля в таблице для кастомных значений юзера
            initial = {'username': reg_user}

accounts/templates/comment_form.html
<form action="{% url 'publication' pub.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in comment_form %}
 
            {% if field.errors %}
                <div>
                    {{ field.errors }}
                </div>
            {% endif %}

            {% if field.label != 'Author' %}
                {% if field.label != 'Pub' %}

                    {{ field }}

                {% endif %}
            {% endif %}


    {% endfor %}
    <button type="submit" name="button">+</button>

</form>

accounts/templates/create_post.html
{% extends 'index.html' %}
{% load static %}



{% block content %}

    <div class="create-post-block">

    <h1 class="section-name-h1">Создать пост</h1>

    <form action="{% url 'create_post_url' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <div>
                {% if field.errors %}
                    <div>
                        {{ field.errors }}
                    </div>
                {% endif %}

                {% if field.label == 'Author' %}
    
                {% elif field.label == 'Введите текст публикации' %}
                    <div class="create-pub-text">
                        <label for="#">Введите текст публикации</label>
                        {{ field }}
                    </div>
                {% elif field.label == 'Загрузите фото' %}
                    <div class="create-pub-img">
                        <label for="id_pub_pic" class="load-pic-label"><span>Выбрать фото</span></label>
                        {{ field }}
                    </div>
                {% endif %}

            </div>
        {% endfor %}
        <div class="create-post-button">
            <button type="submit" name="button" class="create-post-button">+</button>
        </div>
        

    </form>

    </div>




{% endblock %}

{% block extra_js %}
<script src="{% static 'js/load_image.js' %}" type="text/javascript"></script>
{% endblock %}

accounts/templates/feed.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


    <h1 class="section-name-h1">Публикации</h1>

    <h3 class="section-name-h3">Из ваших подписок</h3>
    <br>


    <div class="publications-fullwidth">
    {% if feed_pubs %}

        {% for pub in feed_pubs %}
        

            {% if pub.author in user_info.subscriptions.all %}
            <div class="publication">   
                    <div class="pub-top">
                    <div class="container-90">
                            <div class="pub-top-vertical-align">
                                <a href="{% url 'profile' pub.author.username %}">
                                <img class="pub-img-profile"
                                        width="35px" src="{{ pub.author.profile_info.profile_pic.url }}" 
                                        alt="Фото профиля">
                                <h3>{{pub.author.username}}</h3>
                                </a>
                            </div>
                    </div>
                    </div>
                    
                    <a href="{% url 'publication' pub.id %}"><div class="pub-img-div"><img src="{{ pub.pub_pic.url }}" alt="Фото" class="pub-img"></div></a>

                    <div class="pub-bottom">
                    <div class="container-90">
    
                           
                        {% include 'like_button.html' %}

                        <p><b>{{pub.author.username}}</b> {{pub.pub_text}}</p>
                        <p class="pub-date">{{pub.pub_date}}</p>
                    </div>
                    </div>

            </div>  
            {% elif pub.author.username == user.username %}
            <div class="publication">   
                <div class="pub-top">
                    <div class="container-90">
                            <div class="pub-top-vertical-align">
                                <a href="{% url 'profile' pub.author.username %}">
                                <img class="pub-img-profile"
                                        width="35px" src="{{ pub.author.profile_info.profile_pic.url }}" 
                                        alt="Фото профиля">
                                <h3>{{pub.author.username}}</h3>
                                </a>
                            </div>
                    </div>
                </div>
                    
                    <a href="{% url 'publication' pub.id %}"><div class="pub-img-div"><img src="{{ pub.pub_pic.url }}" alt="Фото" class="pub-img"></div></a>

                    <div class="pub-bottom">
                    <div class="container-90">
       
                        {% include 'like_button.html' %}

                        <p><b>{{pub.author.username}}</b> {{pub.pub_text}}</p>
                        <p class="pub-date">{{pub.pub_date}}</p>
                    </div>
                    </div>
            </div>
            {% endif %}
        

        {% endfor %}
    {% endif %}
    </div>

{% endblock %}

accounts/templates/index.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'static/css/style.css' %}">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <title>davadzh сайт</title>
    
</head>
<body>
    
    {% block header %}
    <div class = "nav-bar-mobile-logo">
        <div class="container">
        {% if user.is_authenticated %}
            <h1><a href="{% url 'feed' %}">inSTONKSgram</a></h1>  
        {% else %}
            <h1>inSTONKSgram</h1> 
        {% endif %}
        </div>
    </div>
    <div class = "nav-bar">
        <div class="container">
        {% if user.is_authenticated %}
            <h1><a href="{% url 'feed' %}">inSTONKSgram</a></h1>
            <ul style="float: right;">
                <li><a href="{% url 'feed' %}"><img src="{% static 'static/images/home.png' %}" alt="Домой" class="nav-icon"></a></li>
                <li><a href="{% url 'recomend' %}"><img src="{% static 'static/images/news.png' %}" alt="Рекомендации" class="nav-icon"></a></li>
                <li><a href="{% url 'create_post_url' %}"><img src="{% static 'static/images/add.png' %}" alt="Создать публикацию" class="nav-icon"></a></li>
                <li><a href="{% url 'notifications' %}"><img src="{% static 'static/images/notifications.png' %}" alt="Уведомления" class="nav-icon"></a></li>
                <li><a href="{% url 'profile' user.username %}"><img src="{% static 'static/images/profile.png' %}" alt="Профиль" class="nav-icon"></a></li>
            </ul>   
        {% else %}
                <ul>
                    <li><a href="{% url 'login_url' %}">Войти</a></li>
                    <li><a href="{% url 'register_url' %}">Регистрация</a></li>
                </ul>
            
        {% endif %}
        </div>
    </div>

    {% endblock %}

    <div class="content">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    </div>


</body>

</html>

accounts/templates/like_button.html
{% load static %}



<div id="like-section-{{ pub.id }}"> 
<div class="like-section">   
    <div class="form-in-past">
    {% if user in pub.pub_likes.all %}
    <button value='{{ pub.id }}' id="like-{{ pub.id }}" name="post_id" type="submit" class="like-button">
        <img src="{% static 'static/images/like_active.png' %}" alt="Like" class="like-button-active">
    </button> 
    {% elif user not in pub.pub_likes.all %}
    <button value='{{ pub.id }}' id="like-{{ pub.id }}" name="post_id" type="submit" class="like-button">
        <img src="{% static 'static/images/like_passive.png' %}" alt="Like" class="like-button-passive">
    </button>
        
        
    {% endif %}
    </div>
    <p class="like-counter">Лайков {{pub.total_likes}}</p>

</div>
</div>

<script>
    $("#like-{{pub.id}}").click(function(event){
        $.ajax({
            method: "POST",
            url: "{% url 'like_url' %}",
            data: {csrfmiddlewaretoken: "{{ csrf_token }}", post_id: "{{ pub.id }}"},
            dataType: 'json',
            success: function(response){
                $('#like-section-{{ pub.id }}').html(response['cont']);
            }
        });
    });
</script>
    
    

accounts/templates/notifications.html
{% extends 'index.html' %}

{% block content %}

    <h1 class="section-name-h1">Уведомления</h1>

    <div class="notifications-block">
    {% if nots %}
    
        {% for n in nots %}
        <div class="notification">
            <h4><a href="{% url 'profile' n.notification_from %}">{{n.notification_from}}</a> {{n.notification_text}}</h4>
            <p>{{n.not_date}}</p>

        </div>
        {% endfor %}
    
    {% else %}
    <div class="notification">
        <h3>У вас нет новых уведомлений</h3>
    </div>
    {% endif %}

    </div>



{% endblock %}

accounts/templates/profile.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


    <!-- Если авторизован, смотрит свой профиль -->
    <div class="profile-head">
    <div class="head-content">
        <div class="profile-img-and-username">
            <img src="{{current_user.profile_pic.url}}" alt="Фото профиля">
            <h1>{{current_user.username.username}}</h1>
        </div>
        
        <div class="profile-info">
            <h3>{{ current_user.name }}</h3>
            <p>Подписчиков: {{ current_user.total_subs }}</p>
            <p>Подписок: {{ current_user.total_subscr }}</p>
            <p>Телефон: {{ current_user.phone }}</p>
            <p>Почта: {{ current_user.email }}</p>
        </div>
    


    {% if current_user.username.username == user.username %}
        <div class="profile-edit-or-exit">
            <a href="{% url 'profile_edit' %}" class="p-edit">Редактировать профиль</a>
            <a href="{% url 'logout' %}" class="p-exit">Выйти</a>
        </div>  
    {% else %}


        {% if user in current_user.subscribers.all %}
            <!-- Отписка -->
            <div class="subscription-button">
                <a href="{% url 'subscription' current_user.username.id %}" class="unsub">Отписаться</a>
            </div>
        {% else %}
            <!-- Подписка -->
            <div class="subscription-button">
                <a href="{% url 'subscription' current_user.username.id %}" class="sub">Подписаться</a>
            </div>
        {% endif %}
        
    {% endif %}
    
    </div>
    </div>
    

    <div class="publications">
    {% if all_pubs %}

        {% for pub in all_pubs %}
        <div class="publication">
            <div class="pub-top">
            <div class="container-90">
                    <div class="pub-top-vertical-align">
                        <a href="{% url 'profile' pub.author.username %}">
                        <img class="pub-img-profile"
                                width="35px" src="{{ pub.author.profile_info.profile_pic.url }}" 
                                alt="Фото профиля">
                        <h3>{{pub.author.username}}</h3>
                        </a>
                    </div>
            </div>
            </div>
            
            <a href="{% url 'publication' pub.id %}"><div class="pub-img-div"><img src="{{ pub.pub_pic.url }}" alt="Фото" class="pub-img"></div></a>

            <div class="pub-bottom">
            <div class="container-90">

                
                        {% include 'like_button.html' %}


                <p><b>{{pub.author.username}}</b> {{pub.pub_text}}</p>
                <p class="pub-date">{{pub.pub_date}}</p>
            </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
    
        <div class="publication-none">
        {% if current_user.username.username == user.username %}
            <h3>У вас пока нет публикаций.</h3> 
        
            <div class="create-first">
                <a href="{% url 'create_post_url' %}" class="create-first-button">Добавьте первую!</a>
            </div>
        {% else %}
            <h3>У пользователя пока нет публикаций</h3>
        {% endif %}
        </div>

    {% endif %}

    </div>

{% endblock %}

accounts/templates/profile_edit.html
{% extends 'index.html' %}

{% block content %}

    <div class="profile-edit-block">
        <h1 class="section-name-h1">Редактировать профиль</h1>

        <form action="{% url 'profile_edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                    {% if field.errors %}
                        <div>
                            {{ field.errors }}
                        </div>
                    {% endif %}

                    {% if field.label == 'Username' %}
                    {% elif field.label == 'Subscribers' %}

                    {% elif field.label == 'Subscriptions' %}
 
                    {% endif %}
                    {% if field.label == 'Name' %}
                        <div class="edit-profile-text">
                            <label>Имя</label>
                            <input type="text" name="name" maxlength="50" id="id_name" value="{{user.profile_info.name}}">
                        </div>
                    {% elif field.label == 'Phone' %}
                        <div class="edit-profile-text">
                            <label>Телефон</label>
                            <input type="text" name="phone" maxlength="50" id="id_phone" value="{{user.profile_info.phone}}">
                        </div>
                    {% elif field.label == 'Email' %}
                        <div class="edit-profile-text">
                            <label>Email</label>
                            <input type="text" name="email" maxlength="50" id="id_email" value="{{user.profile_info.email}}">
                        </div>
                    {% elif field.label == 'Profile pic' %}
                        <div class="create-pub-img">
                            <label for="id_profile_pic" class="load-pic-label">Фото профиля</label>
                            <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
                        </div>
                    {% endif %}
            {% endfor %}
            <button type="submit" name="button">ОК</button>

        </form>
    </div> 

{% endblock %}

accounts/templates/publication.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


    {% if pub %}
    <div class="publication">
        <div class="pub-top">
        <div class="container-90">
                <div class="pub-top-vertical-align">
                    <a href="{% url 'profile' pub.author.username %}">
                    <img class="pub-img-profile"
                            width="35px" src="{{ pub.author.profile_info.profile_pic.url }}" 
                            alt="Фото профиля">
                    <h3>{{pub.author.username}}</h3>
                    </a>
                </div>

                {% if user.username == pub.author.username %}
                <div class="delete-post">
                    <a href="{% url 'pub_delete' pub.id %}">
                        <img src="{% static 'static/images/trash.png' %}">
                    </a>
                </div>
                {% endif %}
                
        </div>
        </div>
        
        <a href="{% url 'publication' pub.id %}"><div class="pub-img-div"><img src="{{ pub.pub_pic.url }}" alt="Фото" class="pub-img"></div></a>

        <div class="pub-bottom">
        <div class="container-90">

            
                    {% include 'like_button.html' %}

            <p><b>{{pub.author.username}}</b> {{pub.pub_text}}</p>
            <p class="pub-date">{{pub.pub_date}}</p>
        </div>
        </div>
    </div>

    <div class="publication-comments">

        <div class="comments-h1-block">
            <h1 class="section-name-h1">Комментарии</h1>
        </div>

        <div class="publication-comment-post">

            {% include 'comment_form.html' %}

        </div>

        <div class="publication-comments-all">
    
            {% for every_comm in comments_of_pub %}
                <div class="publication-comments-one-comment">
                    <h4><b><a href="{% url 'profile' every_comm.author.username %}">{{every_comm.author.username}}</a></b>  {{every_comm.comment_text}}</h4>
                    <p>{{every_comm.comment_date}}</p>
                </div>
            {% endfor %}

        </div>
    
    </div>

    {% else %}

    <h3 class="section-name-h3">Публикация не найдена</h3>

    {% endif %}

{% endblock %}